"order.reserved":
  num_partitions: 3
  replication_factor: 2
  config:
    cleanup.policy: "compact"
    retention.ms: "604800000" # 7 days
    max.message.bytes: 1000000
    delete.retention.ms: "86400000" # 1 day
    compression.type: "lz4"
"order.placed":
  num_partitions: 3
  replication_factor: 2
  config:
    cleanup.policy: "compact"
    retention.ms: "604800000" # 7 days
    max.message.bytes: 1000000
    delete.retention.ms: "86400000" # 1 day
    compression.type: "lz4"
"order.confirmed":
  num_partitions: 3
  replication_factor: 2
  config:
    cleanup.policy: "compact"
    retention.ms: "604800000" # 7 days
    max.message.bytes: 1000000
    delete.retention.ms: "86400000" # 1 day
    compression.type: "lz4"
"order.cancelled":
  num_partitions: 3
  replication_factor: 2
  config:
    cleanup.policy: "compact"
    retention.ms: "604800000" # 7 days
    max.message.bytes: 1000000
    delete.retention.ms: "86400000" # 1 day
    compression.type: "lz4"
"stock.updated":
  num_partitions: 3
  replication_factor: 2
  config:
    cleanup.policy: "compact"
    retention.ms: "604800000" # 7 days
    max.message.bytes: 1000000
    delete.retention.ms: "86400000" # 1 day
    compression.type: "lz4"
"service.logs":
  num_partitions: 6
  replication_factor: 2
  config:
    cleanup.policy: "delete"
    retention.ms: "259200000" # 3 days
    max.message.bytes: 2000000
    compression.type: "gzip"
